Feature/type of ajax
FedorMutovin/advanced_rails pull request #5
Opened 2020-11-09 12:07 UTC by FedorMutovin

2020-11-09 13:33 UTC, IvanShamatov requested changes

2020-11-09 13:33 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +  def wrong_change!
беда с неймингом, и встречается 1 раз, непонятно, зачем выносить в отдельный метод

2020-11-09 13:33 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +  def not_delete!
а что если в контроллере, в который это инклудится тоже есть метод not_delete! ?
Я бы избавился от этого метода, а вообще delete_vote это тоже самое что vote(0)

2020-11-09 13:33 UTC, IvanShamatov commented on app/javascript/packs/votes.js
> +        location.reload()
а зачем тут релоад?

2020-11-09 13:33 UTC, IvanShamatov commented on app/models/answer.rb
> +  def votes_sum
я с этим ок, потому что только один метод повторяется, но в целом, можно было тоже в модуль вынести.
Если бы мы делали какие-нибудь презентеры, то оно бы однозначно хранилось там

2020-11-09 13:33 UTC, IvanShamatov commented on spec/controllers/concerns/voted_spec.rb
> +    context "Not author can delete his vote" do
я читаю спеку и не могу понять, что тут происходит
не автор может удалить свой голос, а ниже автор не может удалить голос
автор чего, автор голоса? автор ответа/вопроса?

2020-11-09 13:33 UTC, IvanShamatov commented on spec/controllers/concerns/voted_spec.rb
> +        expect { post :vote_for, params: { id: resource }, format: :json }.to change(Vote, :count).by 1
я бы еще добавил проверку, что именно у ресурса изменился счетчик голосов, а не вообще у всего на свете изменился счетчик голосов

2020-11-09 15:27 UTC, FedorMutovin commented on app/javascript/packs/votes.js
> +        location.reload()
Для того, чтобы в моменте изменить линки vote_for и  vote_against на delete_vote без перезагрузки страницы

2020-11-09 16:08 UTC, FedorMutovin commented on app/models/answer.rb
> +  def votes_sum
Решил убрать, потому что он использовался только в одном месте

2020-11-09 16:09 UTC, FedorMutovin commented on app/controllers/concerns/voted.rb
> +  def not_delete!
Но для vote(0) придется прописать дополнительные проверки,т.к по условиям проголосовать можно только один раз и это осложнит логику самого удаления на мой взгляд

2020-11-10 06:06 UTC, IvanShamatov commented on app/javascript/packs/votes.js
> +        location.reload()
так это же и есть перезагрузка страницы...

2020-11-10 06:07 UTC, IvanShamatov approved these changes

2020-11-10 06:13 UTC, IvanShamatov commented on app/javascript/packs/votes.js
> +        location.reload()
тут в любом случае не нужно этого делать, 
сумму вставить через jquery, и линки обновить через jquery

2020-11-16 09:40 UTC, merged